import "dotenv/config";
import mongoose from "mongoose";
import { Route } from "../models/Route.js";

type SeedRoute = {
  name: string;
  fromLocation: string;
  toLocation: string;
  from: string;
  to: string;
  distance: number;
  estimatedTime: number;
  fare: number;
};

const routes: SeedRoute[] = [
  {
    name: "Goro → Megenagna",
    fromLocation: "Goro",
    toLocation: "Megenagna",
    from: "Goro",
    to: "Megenagna",
    distance: 10,
    estimatedTime: 25,
    fare: 20,
  },
  {
    name: "Piassa → Bole",
    fromLocation: "Piassa",
    toLocation: "Bole",
    from: "Piassa",
    to: "Bole",
    distance: 12,
    estimatedTime: 30,
    fare: 25,
  },
  {
    name: "Kality → Mexico",
    fromLocation: "Kality",
    toLocation: "Mexico",
    from: "Kality",
    to: "Mexico",
    distance: 14,
    estimatedTime: 35,
    fare: 30,
  },
  {
    name: "Ayat → Merkato",
    fromLocation: "Ayat",
    toLocation: "Merkato",
    from: "Ayat",
    to: "Merkato",
    distance: 16,
    estimatedTime: 40,
    fare: 35,
  },
  {
    name: "Sarbet → CMC",
    fromLocation: "Sarbet",
    toLocation: "CMC",
    from: "Sarbet",
    to: "CMC",
    distance: 18,
    estimatedTime: 45,
    fare: 40,
  },

  {
    name: "Bole → Megenagna",
    fromLocation: "Bole",
    toLocation: "Megenagna",
    from: "Bole",
    to: "Megenagna",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Mexico → Piassa",
    fromLocation: "Mexico",
    toLocation: "Piassa",
    from: "Mexico",
    to: "Piassa",
    distance: 5,
    estimatedTime: 12,
    fare: 12,
  },
  {
    name: "CMC → Ayat",
    fromLocation: "CMC",
    toLocation: "Ayat",
    from: "CMC",
    to: "Ayat",
    distance: 7,
    estimatedTime: 18,
    fare: 18,
  },
  {
    name: "Merkato → Kality",
    fromLocation: "Merkato",
    toLocation: "Kality",
    from: "Merkato",
    to: "Kality",
    distance: 13,
    estimatedTime: 30,
    fare: 28,
  },
  {
    name: "Sarbet → Bole",
    fromLocation: "Sarbet",
    toLocation: "Bole",
    from: "Sarbet",
    to: "Bole",
    distance: 9,
    estimatedTime: 22,
    fare: 20,
  },

  {
    name: "Gofa → Piassa",
    fromLocation: "Gofa",
    toLocation: "Piassa",
    from: "Gofa",
    to: "Piassa",
    distance: 11,
    estimatedTime: 28,
    fare: 22,
  },
  {
    name: "Lebu → Megenagna",
    fromLocation: "Lebu",
    toLocation: "Megenagna",
    from: "Lebu",
    to: "Megenagna",
    distance: 15,
    estimatedTime: 38,
    fare: 30,
  },
  {
    name: "Jemo → Mexico",
    fromLocation: "Jemo",
    toLocation: "Mexico",
    from: "Jemo",
    to: "Mexico",
    distance: 10,
    estimatedTime: 25,
    fare: 20,
  },
  {
    name: "Summit → Bole",
    fromLocation: "Summit",
    toLocation: "Bole",
    from: "Summit",
    to: "Bole",
    distance: 8,
    estimatedTime: 20,
    fare: 18,
  },
  {
    name: "Kotebe → Piassa",
    fromLocation: "Kotebe",
    toLocation: "Piassa",
    from: "Kotebe",
    to: "Piassa",
    distance: 14,
    estimatedTime: 35,
    fare: 30,
  },

  {
    name: "Akaki → Merkato",
    fromLocation: "Akaki",
    toLocation: "Merkato",
    from: "Akaki",
    to: "Merkato",
    distance: 17,
    estimatedTime: 45,
    fare: 40,
  },
  {
    name: "Lafto → Sarbet",
    fromLocation: "Lafto",
    toLocation: "Sarbet",
    from: "Lafto",
    to: "Sarbet",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Torhailoch → Mexico",
    fromLocation: "Torhailoch",
    toLocation: "Mexico",
    from: "Torhailoch",
    to: "Mexico",
    distance: 5,
    estimatedTime: 12,
    fare: 12,
  },
  {
    name: "Megenagna → Ayat",
    fromLocation: "Megenagna",
    toLocation: "Ayat",
    from: "Megenagna",
    to: "Ayat",
    distance: 7,
    estimatedTime: 18,
    fare: 18,
  },
  {
    name: "Bole → CMC",
    fromLocation: "Bole",
    toLocation: "CMC",
    from: "Bole",
    to: "CMC",
    distance: 9,
    estimatedTime: 22,
    fare: 20,
  },

  {
    name: "Piassa → Merkato",
    fromLocation: "Piassa",
    toLocation: "Merkato",
    from: "Piassa",
    to: "Merkato",
    distance: 4,
    estimatedTime: 10,
    fare: 10,
  },
  {
    name: "Mexico → Sarbet",
    fromLocation: "Mexico",
    toLocation: "Sarbet",
    from: "Mexico",
    to: "Sarbet",
    distance: 3,
    estimatedTime: 8,
    fare: 8,
  },
  {
    name: "CMC → Bole",
    fromLocation: "CMC",
    toLocation: "Bole",
    from: "CMC",
    to: "Bole",
    distance: 9,
    estimatedTime: 22,
    fare: 20,
  },
  {
    name: "Ayat → Summit",
    fromLocation: "Ayat",
    toLocation: "Summit",
    from: "Ayat",
    to: "Summit",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Kality → Akaki",
    fromLocation: "Kality",
    toLocation: "Akaki",
    from: "Kality",
    to: "Akaki",
    distance: 5,
    estimatedTime: 12,
    fare: 12,
  },

  {
    name: "Lebu → Gofa",
    fromLocation: "Lebu",
    toLocation: "Gofa",
    from: "Lebu",
    to: "Gofa",
    distance: 7,
    estimatedTime: 18,
    fare: 18,
  },
  {
    name: "Jemo → Lafto",
    fromLocation: "Jemo",
    toLocation: "Lafto",
    from: "Jemo",
    to: "Lafto",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Summit → Megenagna",
    fromLocation: "Summit",
    toLocation: "Megenagna",
    from: "Summit",
    to: "Megenagna",
    distance: 10,
    estimatedTime: 25,
    fare: 22,
  },
  {
    name: "Kotebe → Ayat",
    fromLocation: "Kotebe",
    toLocation: "Ayat",
    from: "Kotebe",
    to: "Ayat",
    distance: 5,
    estimatedTime: 12,
    fare: 12,
  },
  {
    name: "Akaki → Kality",
    fromLocation: "Akaki",
    toLocation: "Kality",
    from: "Akaki",
    to: "Kality",
    distance: 5,
    estimatedTime: 12,
    fare: 12,
  },

  {
    name: "Lafto → Mexico",
    fromLocation: "Lafto",
    toLocation: "Mexico",
    from: "Lafto",
    to: "Mexico",
    distance: 8,
    estimatedTime: 20,
    fare: 18,
  },
  {
    name: "Torhailoch → Piassa",
    fromLocation: "Torhailoch",
    toLocation: "Piassa",
    from: "Torhailoch",
    to: "Piassa",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Megenagna → Bole",
    fromLocation: "Megenagna",
    toLocation: "Bole",
    from: "Megenagna",
    to: "Bole",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Bole → Piassa",
    fromLocation: "Bole",
    toLocation: "Piassa",
    from: "Bole",
    to: "Piassa",
    distance: 12,
    estimatedTime: 30,
    fare: 25,
  },
  {
    name: "Piassa → Goro",
    fromLocation: "Piassa",
    toLocation: "Goro",
    from: "Piassa",
    to: "Goro",
    distance: 11,
    estimatedTime: 28,
    fare: 22,
  },

  {
    name: "Mexico → Gofa",
    fromLocation: "Mexico",
    toLocation: "Gofa",
    from: "Mexico",
    to: "Gofa",
    distance: 10,
    estimatedTime: 25,
    fare: 20,
  },
  {
    name: "CMC → Summit",
    fromLocation: "CMC",
    toLocation: "Summit",
    from: "CMC",
    to: "Summit",
    distance: 6,
    estimatedTime: 15,
    fare: 15,
  },
  {
    name: "Ayat → Bole",
    fromLocation: "Ayat",
    toLocation: "Bole",
    from: "Ayat",
    to: "Bole",
    distance: 10,
    estimatedTime: 25,
    fare: 22,
  },
  {
    name: "Merkato → Piassa",
    fromLocation: "Merkato",
    toLocation: "Piassa",
    from: "Merkato",
    to: "Piassa",
    distance: 4,
    estimatedTime: 10,
    fare: 10,
  },
  {
    name: "Sarbet → Mexico",
    fromLocation: "Sarbet",
    toLocation: "Mexico",
    from: "Sarbet",
    to: "Mexico",
    distance: 3,
    estimatedTime: 8,
    fare: 8,
  },

  {
    name: "Goro → Bole",
    fromLocation: "Goro",
    toLocation: "Bole",
    from: "Goro",
    to: "Bole",
    distance: 7,
    estimatedTime: 18,
    fare: 18,
  },
  {
    name: "Bole → Goro",
    fromLocation: "Bole",
    toLocation: "Goro",
    from: "Bole",
    to: "Goro",
    distance: 7,
    estimatedTime: 18,
    fare: 18,
  },
  {
    name: "Piassa → CMC",
    fromLocation: "Piassa",
    toLocation: "CMC",
    from: "Piassa",
    to: "CMC",
    distance: 13,
    estimatedTime: 32,
    fare: 28,
  },
  {
    name: "Megenagna → Merkato",
    fromLocation: "Megenagna",
    toLocation: "Merkato",
    from: "Megenagna",
    to: "Merkato",
    distance: 11,
    estimatedTime: 28,
    fare: 22,
  },
  {
    name: "Kality → Bole",
    fromLocation: "Kality",
    toLocation: "Bole",
    from: "Kality",
    to: "Bole",
    distance: 15,
    estimatedTime: 38,
    fare: 30,
  },
];

async function insertRoutes() {
  const mongoUri = process.env.MONGODB_URI;
  if (!mongoUri) {
    throw new Error("MONGODB_URI is required to insert routes");
  }

  const shouldClear = process.env.SEED_CLEAR_ROUTES !== "false";

  await mongoose.connect(mongoUri, {
    serverSelectionTimeoutMS: 5000,
    connectTimeoutMS: 5000,
  });

  try {
    if (shouldClear) {
      await Route.deleteMany({});
    }

    await Route.insertMany(routes);
    console.log("✅ 50 routes inserted successfully");
  } finally {
    await mongoose.connection.close();
  }
}

insertRoutes().catch((error) => {
  console.error("❌ Error inserting routes:", error);
  process.exitCode = 1;
});
